// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXAaLv9iRU5wjuVLm8xEI8C7OtZg6qAE4',
    appId: '1:749657841039:web:eb9514440217ef1bf8fffa',
    messagingSenderId: '749657841039',
    projectId: 'penggajian-df16d',
    authDomain: 'penggajian-df16d.firebaseapp.com',
    storageBucket: 'penggajian-df16d.firebasestorage.app',
    measurementId: 'G-NB0B7RMFM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBha_StLTOBevgyvc1t2KklHQh8pVRhI2k',
    appId: '1:749657841039:android:1c4919161637e744f8fffa',
    messagingSenderId: '749657841039',
    projectId: 'penggajian-df16d',
    storageBucket: 'penggajian-df16d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjIWE7qYwWGpLxFLe0eqLrbXcHNXpNK1s',
    appId: '1:749657841039:ios:adaf92f4f89e31e6f8fffa',
    messagingSenderId: '749657841039',
    projectId: 'penggajian-df16d',
    storageBucket: 'penggajian-df16d.firebasestorage.app',
    iosBundleId: 'com.example.pembayaran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjIWE7qYwWGpLxFLe0eqLrbXcHNXpNK1s',
    appId: '1:749657841039:ios:adaf92f4f89e31e6f8fffa',
    messagingSenderId: '749657841039',
    projectId: 'penggajian-df16d',
    storageBucket: 'penggajian-df16d.firebasestorage.app',
    iosBundleId: 'com.example.pembayaran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXAaLv9iRU5wjuVLm8xEI8C7OtZg6qAE4',
    appId: '1:749657841039:web:99d263feb46cba61f8fffa',
    messagingSenderId: '749657841039',
    projectId: 'penggajian-df16d',
    authDomain: 'penggajian-df16d.firebaseapp.com',
    storageBucket: 'penggajian-df16d.firebasestorage.app',
    measurementId: 'G-NNLKQLS5DE',
  );
}
